# Schema for the configuration files of the marketing_cloud_enhanced module.

marketing_cloud_enhanced.settings:
  type: config_object
  label: 'Marketing Cloud Enhanced settings'
  mapping:
    grant_type:
      type: string
      label: 'Type of access to be granted'
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    validate_json:
      type: boolean
      label: 'Validate JSON'
    do_not_send:
      type: boolean
      label: 'Do not send'
    request_token_url:
      type: string
      label: 'Salesforce auth token request URL'
    base_url:
      type: string
      label: 'Salesforce API URL base'
    login_attempts_max:
      type: integer
      label: 'Max login attempts'
    request_token_wait:
      type: integer
      label: 'Seconds to wait before token re-request'
    token:
      type: string
      label: 'Salesforce auth token'
    requesting_token:
      type: boolean
      label: 'Salesforce auth token request in progress'
